//
// File automatically generated by GenESyS DiffEquations plugin
// Date: 
//
#include <iostream>
#include <string>
//@TODO: Adjust depending on the running path
#include "../source/kernel/simulator/Simulator.h"
#include "../source/kernel/simulator/Model.h"
#include "../source/kernel/simulator/Entity.h"
#include "../source/kernel/simulator/TraceManager.h"
#include "../source/tools/SolverDefaultImpl1.h"

using namespace std;

void _onDispatchEvent_DiffEquations_1(Simulator* simulator, Model* model, Entity* entity) {
	cout << "Running" << endl;
	Solver_if *_solver = new SolverDefaultImpl1(0.000001, 1000.000000);
	delete _solver;
}

extern "C" void onDispatchEvent(Simulator* simulator, Model* model, Entity* entity) {
	try {
		_onDispatchEvent_DiffEquations_1(simulator, model, entity);
	} catch (const std::exception& e) {
		model->getTracer()->traceError("Error while executing onDispatchEvent cpp user code in DiffEquations_1.", e);
	}
}

int main() {
	_onDispatchEvent_DiffEquations_1(nullptr, nullptr, nullptr) ;
	return 0;
}

